name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/mlc_config.json"
        continue-on-error: true
